=======
modLoader="javafml"
loaderVersion="[35,)"
license="ECC Computer College"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="hackathon"
version="1.16.4-1.0.8"
displayName="Hackathon Mod"
updateJSONURL="https://www.ea.com/ja-jp"
displayURL="https://eccmcsv.com/"
logoFile="gravestone.png"
credits="Save Titanfall"
authors="Inui, Tano, Fujio"
description="Generate a death box when you die"
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"